kinematics :
  incoming_momenta: [ p1, p2 ]
  outgoing_momenta: [ p3, p4 ]
  momentum_conservation: [p4, p1 + p2 - p3]
  kinematic_invariants:
    - [mw, 1]
    - [s, 2]
    - [t, 2]
  scalarproduct_rules:
    - [[p1,p1],  0]
    - [[p2,p2],  0]
    - [[p3,p3],  mw^2]
    - [[p1+p2,p1+p2],  s]
    - [[p1-p3,p1-p3],  t]
    - [[p2-p3,p2-p3],  -s-t]
