
   mat[2,3] =(

       + INT[F1x12,0,1,0,1]*zprop[p1 + p2]*Prop[p1 - p3,0]^2*N*gew^3*
      gs^2*gwwz * (
          - 64*Cf*mw^6*cvu*I
          - 64*Cf*mw^6*cau*I
          + 96*Cf*u*mw^4*cvu*I
          + 96*Cf*u*mw^4*cau*I
          - 32*Cf*u^2*mw^2*cvu*I
          - 32*Cf*u^2*mw^2*cau*I
          + 112*Cf*t*mw^4*cvu*I
          + 112*Cf*t*mw^4*cau*I
          - 152*Cf*t*u*mw^2*cvu*I
          - 152*Cf*t*u*mw^2*cau*I
          + 36*Cf*t*u^2*cvu*I
          + 36*Cf*t*u^2*cau*I
          - 72*Cf*t^2*mw^2*cvu*I
          - 72*Cf*t^2*mw^2*cau*I
          + 76*Cf*t^2*u*cvu*I
          + 76*Cf*t^2*u*cau*I
          - 4*Cf*t^2*u^2*mw^(-2)*cvu*I
          - 4*Cf*t^2*u^2*mw^(-2)*cau*I
          + 32*Cf*t^3*cvu*I
          + 32*Cf*t^3*cau*I
          - 20*Cf*t^3*u*mw^(-2)*cvu*I
          - 20*Cf*t^3*u*mw^(-2)*cau*I
          - 8*Cf*t^4*mw^(-2)*cvu*I
          - 8*Cf*t^4*mw^(-2)*cau*I
          + 96*Cf*s*mw^4*cvu*I
          + 96*Cf*s*mw^4*cau*I
          - 32*Cf*s*u^2*cvu*I
          - 32*Cf*s*u^2*cau*I
          - 184*Cf*s*t*mw^2*cvu*I
          - 184*Cf*s*t*mw^2*cau*I
          + 24*Cf*s*t*u*cvu*I
          + 24*Cf*s*t*u*cau*I
          + 8*Cf*s*t*u^2*mw^(-2)*cvu*I
          + 8*Cf*s*t*u^2*mw^(-2)*cau*I
          + 52*Cf*s*t^2*cvu*I
          + 52*Cf*s*t^2*cau*I
          + 18*Cf*s*t^2*u*mw^(-2)*cvu*I
          + 18*Cf*s*t^2*u*mw^(-2)*cau*I
          + 2*Cf*s*t^3*mw^(-2)*cvu*I
          + 2*Cf*s*t^3*mw^(-2)*cau*I
          + 6*Cf*s*t^3*u*mw^(-4)*cvu*I
          + 6*Cf*s*t^3*u*mw^(-4)*cau*I
          + 2*Cf*s*t^4*mw^(-4)*cvu*I
          + 2*Cf*s*t^4*mw^(-4)*cau*I
          + 32*Cf*s^2*mw^2*cvu*I
          + 32*Cf*s^2*mw^2*cau*I
          - 64*Cf*s^2*u*cvu*I
          - 64*Cf*s^2*u*cau*I
          + 20*Cf*s^2*t*cvu*I
          + 20*Cf*s^2*t*cau*I
          - 2*Cf*s^2*t^2*mw^(-2)*cvu*I
          - 2*Cf*s^2*t^2*mw^(-2)*cau*I
          - 4*Cf*s^2*t^2*u*mw^(-4)*cvu*I
          - 4*Cf*s^2*t^2*u*mw^(-4)*cau*I
          - 2*Cf*s^2*t^3*mw^(-4)*cvu*I
          - 2*Cf*s^2*t^3*mw^(-4)*cau*I
          - 32*Cf*s^3*cvu*I
          - 32*Cf*s^3*cau*I
          - 8*Cf*s^3*t*mw^(-2)*cvu*I
          - 8*Cf*s^3*t*mw^(-2)*cau*I
          - 4*Cf*s^3*t^2*mw^(-4)*cvu*I
          - 4*Cf*s^3*t^2*mw^(-4)*cau*I
          + 64*n*Cf*mw^6*cvu*I
          + 64*n*Cf*mw^6*cau*I
          - 96*n*Cf*u*mw^4*cvu*I
          - 96*n*Cf*u*mw^4*cau*I
          + 32*n*Cf*u^2*mw^2*cvu*I
          + 32*n*Cf*u^2*mw^2*cau*I
          - 112*n*Cf*t*mw^4*cvu*I
          - 112*n*Cf*t*mw^4*cau*I
          + 152*n*Cf*t*u*mw^2*cvu*I
          + 152*n*Cf*t*u*mw^2*cau*I
          - 36*n*Cf*t*u^2*cvu*I
          - 36*n*Cf*t*u^2*cau*I
          + 64*n*Cf*t^2*mw^2*cvu*I
          + 64*n*Cf*t^2*mw^2*cau*I
          - 70*n*Cf*t^2*u*cvu*I
          - 70*n*Cf*t^2*u*cau*I
          + 4*n*Cf*t^2*u^2*mw^(-2)*cvu*I
          + 4*n*Cf*t^2*u^2*mw^(-2)*cau*I
          - 22*n*Cf*t^3*cvu*I
          - 22*n*Cf*t^3*cau*I
          + 14*n*Cf*t^3*u*mw^(-2)*cvu*I
          + 14*n*Cf*t^3*u*mw^(-2)*cau*I
          + 6*n*Cf*t^4*mw^(-2)*cvu*I
          + 6*n*Cf*t^4*mw^(-2)*cau*I
          - 96*n*Cf*s*mw^4*cvu*I
          - 96*n*Cf*s*mw^4*cau*I
          + 32*n*Cf*s*u^2*cvu*I
          + 32*n*Cf*s*u^2*cau*I
          + 184*n*Cf*s*t*mw^2*cvu*I
          + 184*n*Cf*s*t*mw^2*cau*I
          - 24*n*Cf*s*t*u*cvu*I
          - 24*n*Cf*s*t*u*cau*I
          - 8*n*Cf*s*t*u^2*mw^(-2)*cvu*I
          - 8*n*Cf*s*t*u^2*mw^(-2)*cau*I
          - 50*n*Cf*s*t^2*cvu*I
          - 50*n*Cf*s*t^2*cau*I
          - 17*n*Cf*s*t^2*u*mw^(-2)*cvu*I
          - 17*n*Cf*s*t^2*u*mw^(-2)*cau*I
          - 5*n*Cf*s*t^3*mw^(-2)*cvu*I
          - 5*n*Cf*s*t^3*mw^(-2)*cau*I
          - 3*n*Cf*s*t^3*u*mw^(-4)*cvu*I
          - 3*n*Cf*s*t^3*u*mw^(-4)*cau*I
          - n*Cf*s*t^4*mw^(-4)*cvu*I
          - n*Cf*s*t^4*mw^(-4)*cau*I
          - 32*n*Cf*s^2*mw^2*cvu*I
          - 32*n*Cf*s^2*mw^2*cau*I
          + 64*n*Cf*s^2*u*cvu*I
          + 64*n*Cf*s^2*u*cau*I
          - 20*n*Cf*s^2*t*cvu*I
          - 20*n*Cf*s^2*t*cau*I
          + 7*n*Cf*s^2*t^2*mw^(-2)*cvu*I
          + 7*n*Cf*s^2*t^2*mw^(-2)*cau*I
          + 2*n*Cf*s^2*t^2*u*mw^(-4)*cvu*I
          + 2*n*Cf*s^2*t^2*u*mw^(-4)*cau*I
          + n*Cf*s^2*t^3*mw^(-4)*cvu*I
          + n*Cf*s^2*t^3*mw^(-4)*cau*I
          + 32*n*Cf*s^3*cvu*I
          + 32*n*Cf*s^3*cau*I
          + 8*n*Cf*s^3*t*mw^(-2)*cvu*I
          + 8*n*Cf*s^3*t*mw^(-2)*cau*I
          + 2*n*Cf*s^3*t^2*mw^(-4)*cvu*I
          + 2*n*Cf*s^3*t^2*mw^(-4)*cau*I
          - 16*n^2*Cf*mw^6*cvu*I
          - 16*n^2*Cf*mw^6*cau*I
          + 24*n^2*Cf*u*mw^4*cvu*I
          + 24*n^2*Cf*u*mw^4*cau*I
          - 8*n^2*Cf*u^2*mw^2*cvu*I
          - 8*n^2*Cf*u^2*mw^2*cau*I
          + 28*n^2*Cf*t*mw^4*cvu*I
          + 28*n^2*Cf*t*mw^4*cau*I
          - 38*n^2*Cf*t*u*mw^2*cvu*I
          - 38*n^2*Cf*t*u*mw^2*cau*I
          + 9*n^2*Cf*t*u^2*cvu*I
          + 9*n^2*Cf*t*u^2*cau*I
          - 14*n^2*Cf*t^2*mw^2*cvu*I
          - 14*n^2*Cf*t^2*mw^2*cau*I
          + 16*n^2*Cf*t^2*u*cvu*I
          + 16*n^2*Cf*t^2*u*cau*I
          - n^2*Cf*t^2*u^2*mw^(-2)*cvu*I
          - n^2*Cf*t^2*u^2*mw^(-2)*cau*I
          + 3*n^2*Cf*t^3*cvu*I
          + 3*n^2*Cf*t^3*cau*I
          - 2*n^2*Cf*t^3*u*mw^(-2)*cvu*I
          - 2*n^2*Cf*t^3*u*mw^(-2)*cau*I
          - n^2*Cf*t^4*mw^(-2)*cvu*I
          - n^2*Cf*t^4*mw^(-2)*cau*I
          + 24*n^2*Cf*s*mw^4*cvu*I
          + 24*n^2*Cf*s*mw^4*cau*I
          - 8*n^2*Cf*s*u^2*cvu*I
          - 8*n^2*Cf*s*u^2*cau*I
          - 46*n^2*Cf*s*t*mw^2*cvu*I
          - 46*n^2*Cf*s*t*mw^2*cau*I
          + 6*n^2*Cf*s*t*u*cvu*I
          + 6*n^2*Cf*s*t*u*cau*I
          + 2*n^2*Cf*s*t*u^2*mw^(-2)*cvu*I
          + 2*n^2*Cf*s*t*u^2*mw^(-2)*cau*I
          + 12*n^2*Cf*s*t^2*cvu*I
          + 12*n^2*Cf*s*t^2*cau*I
          + 4*n^2*Cf*s*t^2*u*mw^(-2)*cvu*I
          + 4*n^2*Cf*s*t^2*u*mw^(-2)*cau*I
          + 2*n^2*Cf*s*t^3*mw^(-2)*cvu*I
          + 2*n^2*Cf*s*t^3*mw^(-2)*cau*I
          + 8*n^2*Cf*s^2*mw^2*cvu*I
          + 8*n^2*Cf*s^2*mw^2*cau*I
          - 16*n^2*Cf*s^2*u*cvu*I
          - 16*n^2*Cf*s^2*u*cau*I
          + 5*n^2*Cf*s^2*t*cvu*I
          + 5*n^2*Cf*s^2*t*cau*I
          - 3*n^2*Cf*s^2*t^2*mw^(-2)*cvu*I
          - 3*n^2*Cf*s^2*t^2*mw^(-2)*cau*I
          - 8*n^2*Cf*s^3*cvu*I
          - 8*n^2*Cf*s^3*cau*I
          - 2*n^2*Cf*s^3*t*mw^(-2)*cvu*I
          - 2*n^2*Cf*s^3*t*mw^(-2)*cau*I
          ));

